server:
  port: 8100
spring:
  application:
    name: spring-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka8761:8761/eureka/,http://eureka8762:8762/eureka/
spring-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule