server:
  port: 9002
spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: spring-provider
          uri: lb://spring-provider
          predicates:
            - Path=/spring-provider/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://eureka8761:8761/eureka/,http://eureka8762:8762/eureka/