server:
  port: 8087
spring:
  application:
    name: spring-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka8761:8761/eureka/,http://eureka8762:8762/eureka/
#spring-provider:
#  ribbon:
#负载均衡策略
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
feign:
  client:
    config:
      SPRING-PROVIDER:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full