server:
  port: 9001
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://eureka8761:8761/eureka/,http://eureka8762:8762/eureka/
turbine:
  appConfig: SPRING-CONSUMER
  clusterNameExpression: "'default'"